name: Reusable CloudFormation deployment job

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      STACK_NAME:
        required: true
        type: string
      CHAIN_NAME:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      PAGERDUTY_INTEGRATION_KEY:
        required: true

jobs:
  deploy:
    name: Deploy AWS Infra by using CloudFormation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Deploy CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ inputs.STACK_NAME }}
          template: aws/cloudformation-template.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            PagerDutyIntegrationKey=${{ secrets.PAGERDUTY_INTEGRATION_KEY }},
            ChainName=${{ inputs.CHAIN_NAME }}
